server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Ab123456}
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    com.example.assignment: INFO


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html


scheduling:
  cron: "0 0/5 * * * ?"
  intervalMinutes: 2


api:
  urls:
    - "https://app.aquark.com.tw/api/raw/Angle2024/240627"
    - "https://app.aquark.com.tw/api/raw/Angle2024/240706"
    - "https://app.aquark.com.tw/api/raw/Angle2024/240708"
    - "https://app.aquark.com.tw/api/raw/Angle2024/240709"
    - "https://app.aquark.com.tw/api/raw/Angle2024/240710"
